"""add stores table

Revision ID: 1ffc8cc238fa
Revises: 6a0046431418
Create Date: 2026-07-15 17:06:48.779010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ffc8cc238fa'
down_revision: Union[str, None] = '6a0046431418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_categories', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('business_categories', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('business_categories', 'slug',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint(op.f('business_categories_slug_key'), 'business_categories', type_='unique')
    op.create_index(op.f('ix_business_categories_slug'), 'business_categories', ['slug'], unique=True)
    op.alter_column('otp_requests', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'generic'::character varying"))
    op.add_column('seller_business_categories', sa.Column('business_category_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('seller_business_categories_category_id_fkey'), 'seller_business_categories', type_='foreignkey')
    op.create_foreign_key(None, 'seller_business_categories', 'business_categories', ['business_category_id'], ['id'])
    op.drop_column('seller_business_categories', 'created_at')
    op.drop_column('seller_business_categories', 'category_id')
    op.drop_column('sellers', 'business_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('business_category', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('seller_business_categories', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('seller_business_categories', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'seller_business_categories', type_='foreignkey')
    op.create_foreign_key(op.f('seller_business_categories_category_id_fkey'), 'seller_business_categories', 'categories', ['category_id'], ['id'])
    op.drop_column('seller_business_categories', 'business_category_id')
    op.alter_column('otp_requests', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'generic'::character varying"))
    op.drop_index(op.f('ix_business_categories_slug'), table_name='business_categories')
    op.create_unique_constraint(op.f('business_categories_slug_key'), 'business_categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('business_categories', 'slug',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('business_categories', 'active')
    op.drop_column('business_categories', 'description')
    # ### end Alembic commands ###
