"""Phase 3 Task 2: marketplace commission engine.

Revision ID: p3_commission_engine
Revises: p3_inventory_reservations
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="p3_commission_engine"
down_revision="p3_inventory_reservations"
branch_labels=None
depends_on=None

def upgrade():
    scope=postgresql.ENUM("global","category","seller","product",name="commissionscope",create_type=False); scope.create(op.get_bind(),checkfirst=True)
    rtype=postgresql.ENUM("percentage","fixed",name="commissionruletype",create_type=False); rtype.create(op.get_bind(),checkfirst=True)
    ttype=postgresql.ENUM("sale","commission","seller_earning","commission_reversal","refund","adjustment","payout",name="marketplacetransactiontype",create_type=False); ttype.create(op.get_bind(),checkfirst=True)
    op.create_table("commission_rules",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("scope",scope,nullable=False),sa.Column("rule_type",rtype,nullable=False),sa.Column("rate",sa.Numeric(10,4),nullable=False),sa.Column("seller_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sellers.id",ondelete="CASCADE")),sa.Column("category_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("categories.id",ondelete="CASCADE")),sa.Column("product_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("products.id",ondelete="CASCADE")),sa.Column("priority",sa.Integer(),nullable=False,server_default="0"),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("starts_at",sa.DateTime(timezone=True)),sa.Column("ends_at",sa.DateTime(timezone=True)),sa.Column("created_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.CheckConstraint("rate >= 0",name="ck_commission_rule_rate_nonnegative"),sa.CheckConstraint("rule_type <> 'percentage' OR rate <= 100",name="ck_commission_percentage_lte_100"),sa.CheckConstraint("ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",name="ck_commission_rule_date_range"),sa.CheckConstraint("(scope = 'global' AND seller_id IS NULL AND category_id IS NULL AND product_id IS NULL) OR (scope = 'seller' AND seller_id IS NOT NULL AND category_id IS NULL AND product_id IS NULL) OR (scope = 'category' AND category_id IS NOT NULL AND seller_id IS NULL AND product_id IS NULL) OR (scope = 'product' AND product_id IS NOT NULL AND seller_id IS NULL AND category_id IS NULL)",name="ck_commission_rule_scope_target"))
    for c in ["scope","seller_id","category_id","product_id","is_active"]: op.create_index(f"ix_commission_rules_{c}","commission_rules",[c])
    op.create_table("order_item_commissions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("order_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("orders.id",ondelete="CASCADE"),nullable=False),sa.Column("order_item_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("order_items.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("seller_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sellers.id",ondelete="RESTRICT"),nullable=False),sa.Column("commission_rule_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("commission_rules.id",ondelete="SET NULL")),sa.Column("currency",sa.String(10),nullable=False),sa.Column("gross_amount",sa.Numeric(18,2),nullable=False),sa.Column("commission_rate",sa.Numeric(10,4),nullable=False),sa.Column("commission_amount",sa.Numeric(18,2),nullable=False),sa.Column("seller_net_amount",sa.Numeric(18,2),nullable=False),sa.Column("processing_fee",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("tax_amount",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("gross_amount >= 0",name="ck_item_commission_gross_nonnegative"),sa.CheckConstraint("commission_amount >= 0",name="ck_item_commission_amount_nonnegative"),sa.CheckConstraint("seller_net_amount >= 0",name="ck_item_commission_net_nonnegative"))
    for c in ["order_id","order_item_id","seller_id"]: op.create_index(f"ix_order_item_commissions_{c}","order_item_commissions",[c])
    op.create_table("marketplace_transactions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("order_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("orders.id",ondelete="CASCADE"),nullable=False),sa.Column("order_item_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("order_items.id",ondelete="CASCADE")),sa.Column("seller_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sellers.id",ondelete="RESTRICT")),sa.Column("commission_record_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("order_item_commissions.id",ondelete="CASCADE")),sa.Column("transaction_type",ttype,nullable=False),sa.Column("currency",sa.String(10),nullable=False),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("reference",sa.String(180),nullable=False,unique=True),sa.Column("description",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("amount >= 0",name="ck_marketplace_transaction_amount_nonnegative"))
    for c in ["order_id","order_item_id","seller_id","commission_record_id","transaction_type","reference"]: op.create_index(f"ix_marketplace_transactions_{c}","marketplace_transactions",[c])

def downgrade():
    op.drop_table("marketplace_transactions"); op.drop_table("order_item_commissions"); op.drop_table("commission_rules")
    for name in ["marketplacetransactiontype","commissionruletype","commissionscope"]: postgresql.ENUM(name=name).drop(op.get_bind(),checkfirst=True)
