"""Phase 3 Task 4 refund and reversal engine.
Revision ID: p3_refund_engine
Revises: p3_seller_wallets
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="p3_refund_engine"
down_revision="p3_seller_wallets"
branch_labels=None
depends_on=None
def upgrade():
    rs=postgresql.ENUM("requested","under_review","approved","processing","completed","rejected","failed","cancelled",name="refundstatus",create_type=False);rs.create(op.get_bind(),checkfirst=True)
    rr=postgresql.ENUM("changed_mind","damaged","defective","wrong_item","not_received","duplicate_payment","other",name="refundreason",create_type=False);rr.create(op.get_bind(),checkfirst=True)
    im=postgresql.ENUM("refund_restock","refund_damaged","manual_adjustment",name="inventorymovementtype",create_type=False);im.create(op.get_bind(),checkfirst=True)
    op.add_column("seller_wallets",sa.Column("debt_balance",sa.Numeric(18,2),nullable=False,server_default="0"))
    op.drop_constraint("ck_wallet_balances_nonnegative","seller_wallets",type_="check")
    op.create_check_constraint("ck_wallet_balances_nonnegative","seller_wallets","pending_balance >= 0 AND available_balance >= 0 AND reserved_balance >= 0 AND paid_out_balance >= 0 AND refunded_balance >= 0 AND debt_balance >= 0")
    op.create_table("refunds",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("order_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("orders.id",ondelete="RESTRICT"),nullable=False),sa.Column("requested_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",rs,nullable=False,server_default="requested"),sa.Column("reason",rr,nullable=False),sa.Column("reason_details",sa.Text()),sa.Column("currency",sa.String(10),nullable=False),sa.Column("items_amount",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("shipping_amount",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("tax_amount",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("total_amount",sa.Numeric(18,2),nullable=False),sa.Column("provider_reference",sa.String(180),unique=True),sa.Column("idempotency_key",sa.String(180),nullable=False,unique=True),sa.Column("admin_note",sa.Text()),sa.Column("requested_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("processed_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.CheckConstraint("items_amount >= 0 AND shipping_amount >= 0 AND tax_amount >= 0 AND total_amount > 0",name="ck_refund_amounts_valid"));
    for c in ["order_id","requested_by_id","status","provider_reference","idempotency_key"]:op.create_index(f"ix_refunds_{c}","refunds",[c],unique=c in {"provider_reference","idempotency_key"})
    op.create_table("refund_items",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("refund_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("refunds.id",ondelete="CASCADE"),nullable=False),sa.Column("order_item_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("order_items.id",ondelete="RESTRICT"),nullable=False),sa.Column("seller_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sellers.id",ondelete="RESTRICT"),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.Column("unit_amount",sa.Numeric(18,2),nullable=False),sa.Column("refund_amount",sa.Numeric(18,2),nullable=False),sa.Column("commission_reversal",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("seller_reversal",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("seller_debt_amount",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("restock",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("processed_at",sa.DateTime(timezone=True)),sa.CheckConstraint("quantity > 0 AND unit_amount >= 0 AND refund_amount > 0 AND commission_reversal >= 0 AND seller_reversal >= 0 AND seller_debt_amount >= 0",name="ck_refund_item_values_valid"),sa.UniqueConstraint("refund_id","order_item_id",name="uq_refund_item_per_refund"));
    for c in ["refund_id","order_item_id","seller_id"]:op.create_index(f"ix_refund_items_{c}","refund_items",[c])
    op.create_table("refund_events",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("refund_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("refunds.id",ondelete="CASCADE"),nullable=False),sa.Column("status",rs,nullable=False),sa.Column("note",sa.Text()),sa.Column("created_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()));op.create_index("ix_refund_events_refund_id","refund_events",["refund_id"])
    op.create_table("inventory_movements",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("inventory_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("inventory.id",ondelete="RESTRICT"),nullable=False),sa.Column("order_item_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("order_items.id",ondelete="SET NULL")),sa.Column("refund_item_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("refund_items.id",ondelete="SET NULL"),unique=True),sa.Column("movement_type",im,nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.Column("before_quantity",sa.Integer(),nullable=False),sa.Column("after_quantity",sa.Integer(),nullable=False),sa.Column("note",sa.Text()),sa.Column("created_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("quantity > 0 AND before_quantity >= 0 AND after_quantity >= 0",name="ck_inventory_movement_values_valid"));op.create_index("ix_inventory_movements_inventory_id","inventory_movements",["inventory_id"]);op.create_index("ix_inventory_movements_movement_type","inventory_movements",["movement_type"])
def downgrade():
    op.drop_table("inventory_movements");op.drop_table("refund_events");op.drop_table("refund_items");op.drop_table("refunds")
    op.drop_constraint("ck_wallet_balances_nonnegative","seller_wallets",type_="check");op.create_check_constraint("ck_wallet_balances_nonnegative","seller_wallets","pending_balance >= 0 AND available_balance >= 0 AND reserved_balance >= 0 AND paid_out_balance >= 0 AND refunded_balance >= 0");op.drop_column("seller_wallets","debt_balance")
    im=postgresql.ENUM(name="inventorymovementtype");im.drop(op.get_bind(),checkfirst=True);rr=postgresql.ENUM(name="refundreason");rr.drop(op.get_bind(),checkfirst=True);rs=postgresql.ENUM(name="refundstatus");rs.drop(op.get_bind(),checkfirst=True)
