"""Phase 3 Task 3 seller wallets and payouts.
Revision ID: p3_seller_wallets
Revises: p3_commission_engine
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="p3_seller_wallets"
down_revision="p3_commission_engine"
branch_labels=None
depends_on=None
def upgrade():
    wt=postgresql.ENUM("sale_credit","funds_release","payout_hold","payout_completed","payout_released","refund_debit","adjustment",name="wallettransactiontype",create_type=False); wt.create(op.get_bind(),checkfirst=True)
    ps=postgresql.ENUM("pending","approved","processing","completed","rejected","failed","cancelled",name="payoutstatus",create_type=False); ps.create(op.get_bind(),checkfirst=True)
    op.create_table("seller_wallets",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("seller_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sellers.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("currency",sa.String(10),nullable=False,server_default="TZS"),sa.Column("pending_balance",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("available_balance",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("reserved_balance",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("paid_out_balance",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("refunded_balance",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("is_frozen",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.CheckConstraint("pending_balance >= 0 AND available_balance >= 0 AND reserved_balance >= 0 AND paid_out_balance >= 0 AND refunded_balance >= 0",name="ck_wallet_balances_nonnegative")); op.create_index("ix_seller_wallets_seller_id","seller_wallets",["seller_id"],unique=True); op.create_index("ix_seller_wallets_is_frozen","seller_wallets",["is_frozen"])
    op.create_table("payout_requests",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("wallet_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("seller_wallets.id",ondelete="RESTRICT"),nullable=False),sa.Column("seller_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("sellers.id",ondelete="RESTRICT"),nullable=False),sa.Column("payout_account_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("seller_payout_accounts.id",ondelete="RESTRICT"),nullable=False),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(10),nullable=False),sa.Column("status",ps,nullable=False,server_default="pending"),sa.Column("provider_reference",sa.String(180),unique=True),sa.Column("seller_note",sa.Text()),sa.Column("admin_note",sa.Text()),sa.Column("requested_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("processed_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.CheckConstraint("amount > 0",name="ck_payout_amount_positive")); op.create_index("ix_payout_requests_wallet_id","payout_requests",["wallet_id"]); op.create_index("ix_payout_requests_seller_id","payout_requests",["seller_id"]); op.create_index("ix_payout_requests_status","payout_requests",["status"])
    op.create_table("wallet_transactions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("wallet_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("seller_wallets.id",ondelete="CASCADE"),nullable=False),sa.Column("transaction_type",wt,nullable=False),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(10),nullable=False),sa.Column("reference",sa.String(180),nullable=False,unique=True),sa.Column("order_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("orders.id",ondelete="SET NULL")),sa.Column("order_item_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("order_items.id",ondelete="SET NULL")),sa.Column("payout_request_id",postgresql.UUID(as_uuid=True)),sa.Column("eligible_at",sa.DateTime(timezone=True)),sa.Column("released_at",sa.DateTime(timezone=True)),sa.Column("description",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("amount >= 0",name="ck_wallet_transaction_amount_nonnegative")); op.create_index("ix_wallet_transactions_wallet_id","wallet_transactions",["wallet_id"]); op.create_index("ix_wallet_transactions_transaction_type","wallet_transactions",["transaction_type"]); op.create_index("ix_wallet_transactions_reference","wallet_transactions",["reference"],unique=True); op.create_index("ix_wallet_transactions_eligible_at","wallet_transactions",["eligible_at"])
    op.create_table("payout_events",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("payout_request_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("payout_requests.id",ondelete="CASCADE"),nullable=False),sa.Column("status",ps,nullable=False),sa.Column("note",sa.Text()),sa.Column("created_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now())); op.create_index("ix_payout_events_payout_request_id","payout_events",["payout_request_id"])
def downgrade():
    op.drop_table("payout_events"); op.drop_table("wallet_transactions"); op.drop_table("payout_requests"); op.drop_table("seller_wallets"); postgresql.ENUM(name="payoutstatus").drop(op.get_bind(),checkfirst=True); postgresql.ENUM(name="wallettransactiontype").drop(op.get_bind(),checkfirst=True)
